version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          command: ./gradlew assembleRelease

  test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          command: ./gradlew test

  lint:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          command: .gradlew/ktlint

workflows:
  android:
    jobs:
      - build
      - test
      - lint